version: 2

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - misspell
    - gosec
    - revive

linters-settings:
  errcheck:
    check-type-assertions: true
    
  govet:
    enable-all: true
    
  misspell:
    locale: US
    
  gosec:
    severity: medium
    confidence: medium
      
  revive:
    rules:
      - name: exported
      - name: error-return
      - name: error-naming
      - name: var-naming
      - name: context-as-argument
      - name: error-strings

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: cmd/
      linters:
        - revive
