run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gosec
    - revive
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - exportloopref
    - nilerr
    - nolintlint
    - stylecheck
    - whitespace
  disable:
    - typecheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    
  govet:
    check-shadowing: true
    enable-all: true
    
  gofmt:
    simplify: true
    
  goimports:
    local-prefixes: github.com/timkrebs/go-microservice
    
  misspell:
    locale: US
    
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G404  # Use of weak random number generator
      
  revive:
    rules:
      - name: exported
        severity: warning
      - name: error-return
        severity: warning
      - name: error-naming
        severity: warning
      - name: if-return
        severity: warning
      - name: var-naming
        severity: warning
      - name: package-comments
        severity: warning
      - name: range
        severity: warning
      - name: blank-imports
        severity: warning
      - name: context-as-argument
        severity: warning
      - name: dot-imports
        severity: warning
      - name: error-strings
        severity: warning
      - name: increment-decrement
        severity: warning
      - name: var-declaration
        severity: warning
        
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]
    
  nakedret:
    max-func-lines: 30
    
  prealloc:
    simple: true
    range-loops: true
    for-loops: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam
    - path: cmd/
      linters:
        - gocyclo
        - funlen
    - linters:
        - stylecheck
      text: "ST1003:"
    - linters:
        - revive
      text: "package-comments"
      
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  
severity:
  default-severity: error
