run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional recommended linters
    - gocritic
    - gofmt
    - goimports
    - misspell

    # Security linters
    - gosec

    # Performance linters
    - prealloc

    # Style linters
    - revive
    - unconvert
    - unparam

    # Bug detection
    - bodyclose
    - nilerr
    - nilnil

    # Code complexity
    - cyclop
    - gocognit

  disable:
    # Too strict for most projects
    - wsl
    - nlreturn
    - gochecknoglobals
    - gochecknoinits
    - exhaustive
    - exhaustruct
    - varnamelen
    - ireturn
    - nonamedreturns

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too strict, micro-optimization

  misspell:
    locale: US

  goimports:
    local-prefixes: github.com/timkrebs/image-processor

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam  # Can be too strict
      - rangeValCopy  # Can be too strict

  revive:
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
        disabled: true  # Too strict for internal packages
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
        disabled: true  # Handled by unparam
      - name: unreachable-code
      - name: redefines-builtin-id

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Audit errors not checked (too noisy)
      - G304  # File path provided as taint input (common in file handling)

  cyclop:
    max-complexity: 15
    package-average: 0.0
    skip-tests: true

  gocognit:
    min-complexity: 20

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - govet
        - gosec
        - errcheck
        - unparam
        - cyclop
        - gocognit

    # Exclude some linters from running on main.go files
    - path: cmd/
      linters:
        - govet
        - gocognit

    # Allow dot imports in test files for testify
    - path: _test\.go
      text: "dot-imports"

    # Allow unused parameters in interface implementations
    - linters:
        - unparam
      text: "always receives"

    # Allow some common patterns
    - linters:
        - gocritic
      text: "commentFormatting"

    # Exclude "should have comment" errors for internal packages
    - path: internal/
      linters:
        - revive
      text: "exported:"

  exclude-dirs:
    - vendor
    - .git
    - bin

severity:
  default-severity: warning
  case-sensitive: false
  rules:
    - linters:
        - gosec
      severity: error
    - linters:
        - govet
      severity: error
