---
extends: default

rules:
  line-length:
    max: 150
    level: warning
  document-start: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1
  indentation:
    spaces: 2
    indent-sequences: consistent

ignore: |
  deployments/kubernetes/
  .github/workflows/
