apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-processor-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: image-processor-alerts
    notifications.argoproj.io/subscribe.on-health-degraded.slack: image-processor-alerts
spec:
  project: default
  
  source:
    repoURL: https://github.com/timkrebs/go-microservice.git
    targetRevision: main
    path: deployments/kubernetes/overlays/prod
  
  destination:
    server: https://kubernetes.default.svc
    namespace: image-processor-prod
  
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  
  revisionHistoryLimit: 20
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
